services:
  mssql-oldest:
    container_name: sequelize-mssql-oldest
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Password12!
    ports:
      - 22019:1433
    volumes:
      - mssql-oldest:/var/opt/mssql
    security_opt:
      - seccomp:unconfined
    privileged: true
    sysctls:
      net.ipv4.ip_unprivileged_port_start: "0"
    cap_add:
      - SYS_PTRACE
      - SYSLOG
    ulimits:
      memlock: -1
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test:
        [
          'CMD',
          '/opt/mssql-tools/bin/sqlcmd',
          '-S',
          'localhost',
          '-U',
          'SA',
          '-P',
          'Password12!',
          '-l',
          '30',
          '-Q',
          'SELECT 1',
        ]
      interval: 3s
      timeout: 1s
      retries: 10

networks:
  default:
    name: sequelize-mssql-oldest-network

volumes:
  mssql-oldest:
    name: sequelize-mssql-oldest-volume
