name: CI
on:
  push:
    branches:
      - renovate/**
  pull_request:
  merge_group:
  workflow_dispatch:

# workflow_ref includes the branch ref & the file name
# which means a unique run per branch for push & pull_request
# pull_request_target would use the ref of the target branch, which would not be suitable
concurrency:
  group: '${{ github.workflow_ref }}'
  cancel-in-progress: true

jobs:
  install-and-build:
    # We already run the CI on "push" for renovate branches
    if: ${{ github.event_name != 'pull_request' || !startsWith(github.head_ref, 'renovate/') }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    name: Upload install and build artifact (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build sequelize
        run: yarn build
      - name: Reset NX cache
        run: yarn nx reset
      - name: Compress artifact
        run: tar -cf install-build-node-${{ matrix.node-version }}.tar ./packages/*/lib ./node_modules ./packages/*/node_modules
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: install-build-artifact-node-${{ matrix.node-version }}
          path: install-build-node-${{ matrix.node-version }}.tar
          retention-days: 1
  test-mssql-oldest:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    name: mssql oldest (Node ${{ matrix.node-version }})
    runs-on: ubuntu-22.04
    needs: [install-and-build]
    env:
      DIALECT: mssql
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: install-build-artifact-node-${{ matrix.node-version }}
      - name: Extract artifact
        run: tar -xf install-build-node-${{ matrix.node-version }}.tar
      - name: Check Missing Dependencies Early
        run: |
          docker create --name temp_mssql mcr.microsoft.com/mssql/server:2017-latest
          docker cp temp_mssql:/opt/mssql/bin/sqlservr ./sqlservr
          ldd ./sqlservr | grep "not found" || echo "No missing dependencies"
          docker rm temp_mssql
      - run: yarn start-mssql-oldest
      - name: Integration Tests
        run: yarn lerna run test-integration --scope=@sequelize/core
