name: CI
on:
  push:
    branches:
      - renovate/**
  pull_request:
    branches-ignore:
      - renovate/**
  merge_group:
  workflow_dispatch:

# This configuration cancels previous runs if a new run is started on the same PR. Only one run at a time per PR.
# This does not affect pushes to the v7 branch itself, only PRs.
# from https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install-and-build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    name: Upload install and build artifact (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build sequelize
        run: yarn build
      - name: Reset NX cache
        run: yarn nx reset
      - name: Compress artifact
        run: tar -cf install-build-node-${{ matrix.node-version }}.tar ./packages/*/lib ./node_modules ./packages/*/node_modules
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: install-build-artifact-node-${{ matrix.node-version }}
          path: install-build-node-${{ matrix.node-version }}.tar
          retention-days: 1
  test-mssql-oldest:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    name: mssql oldest (Node ${{ matrix.node-version }})
    runs-on: ubuntu-20.04
    needs: install-and-build
    env:
      DIALECT: mssql
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: install-build-artifact-node-${{ matrix.node-version }}
      - name: Extract artifact
        run: tar -xf install-build-node-${{ matrix.node-version }}.tar
      # The following step needs to be removed once we can update to ubuntu-22.04
      - name: Install glibc 2.32 from pre-built binaries
        run: |
          GLIBC_VERSION=2.32
          GLIBC_DOWNLOAD_URL=http://ftp.debian.org/debian/pool/main/g/glibc/glibc_${GLIBC_VERSION}-0ubuntu1_amd64.deb

          # Download the pre-built glibc binary
          wget ${GLIBC_DOWNLOAD_URL} -O /tmp/glibc_${GLIBC_VERSION}.deb
          
          # Install glibc package
          sudo dpkg -i /tmp/glibc_${GLIBC_VERSION}.deb
          sudo apt-get -f install  # Fix any broken dependencies
      - name: Check glibc version
        run: |
          ldd --version
      - run: yarn start-mssql-oldest
      - name: Integration Tests
        run: yarn lerna run test-integration --scope=@sequelize/core